package com.yan.xpay.enums;

public enum AssetOperType {
	RECHARGE,
	WITHDRAW,
	WITHDRAW_REQUEST,
	PAYIN,
	PAYOUT,
	PAYOUT_REQUEST,
	WITHDRAW_REFUND,
	PAYOUT_REFUND,
	FIAT_CURRENCY_PAYIN,
	FIAT_CURRENCY_PAYOUT,
	FIAT_CURRENCY_PAYOUT_REQUEST,
	FIAT_CURRENCY_PAYOUT_REFUND
}
