package com.yan.xpay.enums;

public enum NotifyType {
	ORDER_PENDING,
	ORDER_PENDING_CONFIRMATION,
	ORDER_SUCCESS,
	ORDER_EXPIRED,
	ORDER_FAILED,
	COLLECT_PENDING,
	COLLECT_SUCCESS,
	COLLECT_FAILED,
}
